algo = input('Digite qualquer coisa no teclado:')
print(type(algo))
print('Identificavel:', algo.isidentifier())
print('Digito:', algo.isdigit())
print('Decimal:', algo.isdecimal())
print('ASCII:', algo.isascii())
print('Alfabeto:', algo.isalpha())
print('Espaço:', algo.isspace())
print('Minuscula:', algo.islower())
print('Maiuscula:', algo.isupper())
print('Alpha Numérico:', algo.isalnum())
print('Numérico:', algo.isnumeric())
print('Capitalizado:', algo.istitle())
print('Pode ser exibido na tela:', algo.isprintable())
